### ISSUE TITLE
Cannot make this work?

### ISSUE THREAD

**Issue by joq3** [tripflex/wp-tinymce-placeholder#3]
Hi,

I downloaded the plugin and put it inside the folder of the theme I am currently using.
I use a plugin called Code Snippets and added the code that you provided, and also changed the URL to the script-file, full URL.
When I try to run this, the text-box is gone completely and I get this error:
Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /home/a/ourname/www/signage/wp-includes/class-wp-hook.php on line 298

Any ideas? I really like this plugin, and really need to make it work.

Thank you for the good work!

**Comment by tripflex** [comment]
Sorry that was my fault, I had the filter example set to call a class method instead of a normal function. I updated the readme with the correct code that should work
