### ISSUE TITLE
Uncaught SyntaxError

### ISSUE THREAD

**Issue by Joe-Bloggs** [tripflex/wp-tinymce-placeholder#4]
Hey @tripflex ,

I've been trying out the plugin, but I'm getting "Uncaught SyntaxError: Unexpected token" error in the Chrome developer console.

The error doesn't say much else, just points to the file like this: https://my-domain.com/wp-content/themes/my-child-theme/plugins/mce.placeholder.js?wp-mce-4800-20180716

Any ideas?

**Comment by Joe-Bloggs** [comment]
hm .. I'm not seeing the same error in FF, but the placeholder still won't show.

Here is what I've done:

I put the `mce.placeholder.js` into my child-theme/plugins directory and I called the plugin by the first bit of code:

```
add_filter( 'mce_external_plugins', 'add_mce_placeholder_plugin' );

function add_mce_placeholder_plugin( $plugins ){

    $plugins[ 'placeholder' ] = '//my-domain.com/my-child-theme/plugins/mce.placeholder.js';

    return $plugins;
}
```

Is there anything else here to replace other then the full path to the js file?

Now I want to add a placeholder text to the editor with meta `job_description`

So I'm replacing the default `the_editor` from your code with my `job_description` in the name of this following function:

```
add_filter( 'job_description', 'set_my_mce_editor_placeholder' );

function set_my_mce_editor_placeholder( $textarea_html ){

    $placeholder = __( 'Check it out...this is my custom placeholder!' );

    $textarea_html = preg_replace( '/<textarea/', "<textarea placeholder=\"{$placeholder}\"", $textarea_html );

    return $textarea_html;
}
```

Is there anything else that I should be doing?

**Comment by tripflex** [comment]
@Joe-Bloggs hmm weird ... I just tested this myself and i don't have any issues in Chrome

Can you post a screenshot of the error?  Or figure out where/what it's saying the `Unexpected token` is?  Make sure you copied the code correctly ... check the JS to make sure that you didn't accidentally add anything in the JS code

Also, `//my-domain.com/my-child-theme/plugins/mce.placeholder.js` should probably be `//my-domain.com/wp-content/themes/my-child-theme/plugins/mce.placeholder.js`

**Comment by tripflex** [comment]
Closing due to non response from author @Joe-Bloggs
